wandb:
  project: horse2vec
  exp_num: 2
  exp_name: large_batch
  tags: [LARGR, larget_batch]
path:
  train_dic_path: "/content/drive/MyDrive/卒論/data/train_dict.pkl"
  train_df_path: "/content/drive/MyDrive/卒論/data/preprocessed_data.csv"
  checkpoint_path: checkpoints
  own_sampler_path: "/content/drive/MyDrive/卒論/data/own_sampler.pkl"
  read_trin_dict: true
model:
  d_model: 768
  pad_idx: 187255
  worst_rank: 18
  num_heads: 6
  n_times: 8
  n_added_futures: 17
  dropout: 0.1
training:
  n_epochs: 4000
  batch_size: 1
  val_nun: 1
  learning_rate: 0.00001
  layer_eps: 0.00001
  target_time_key: "time"
  target_rank_key: "rank"
  ranklambda: 90
callbacks:
  patience: 100
  patience_min_delta: 0
  save_top_k: 1